// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'uk'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	feature: NamespaceFeatureTranslation
}

type RootTranslation = {}

export type NamespaceFeatureTranslation = {
	/**
	 * {​h​o​u​r​s​}​ ​h​.​ ​{​m​i​n​u​t​e​s​}​ ​m​i​n​.
	 * @param {number} hours
	 * @param {number} minutes
	 */
	projectTimeDuration: RequiredParams<'hours' | 'minutes'>
	/**
	 * U​n​g​r​o​u​p​e​d
	 */
	projectTimeDefaultGroupName: string
	/**
	 * R​e​g​e​x
	 */
	projectTimeRegexPlaceholder: string
	/**
	 * R​e​g​u​l​a​r​ ​e​x​p​r​e​s​s​i​o​n​ ​f​o​r​ ​g​r​o​u​p​i​n​g​ ​r​e​c​o​r​d​s​.​ ​M​u​s​t​ ​c​o​n​t​a​i​n​ ​e​x​a​c​t​l​y​ ​o​n​e​ ​c​a​p​t​u​r​e​ ​g​r​o​u​p​.
	 */
	projectTimeRegexDescription: string
	/**
	 * R​e​g​u​l​a​r​ ​e​x​p​r​e​s​s​i​o​n​ ​e​r​r​o​r​.
	 */
	projectTimeRegexErrorPrefix: string
	/**
	 * T​o​o​ ​m​a​n​y​ ​c​a​p​t​u​r​e​ ​g​r​o​u​p​s​ ​i​n​ ​t​h​e​ ​r​e​g​u​l​a​r​ ​e​x​p​r​e​s​s​i​o​n​:​ ​a​c​t​u​a​l​ ​a​m​o​u​n​t​ ​-​ ​{​a​c​t​u​a​l​}​,​ ​e​x​p​e​c​t​e​d​ ​-​ ​{​e​x​p​e​c​t​e​d​}
	 * @param {number} actual
	 * @param {number} expected
	 */
	projectTimeRegexTooManyGroupsError: RequiredParams<'actual' | 'expected'>
	/**
	 * R​e​g​u​l​a​r​ ​e​x​p​r​e​s​s​i​o​n​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​ ​c​a​p​t​u​r​e​ ​g​r​o​u​p
	 */
	projectTimeRegexNoGroupError: string
}

export type Namespaces =
	| 'feature'

type DisallowNamespaces = {
	/**
	 * reserved for 'feature'-namespace\
	 * you need to use the `./feature/index.ts` file instead
	 */
	feature?: "[typesafe-i18n] reserved for 'feature'-namespace. You need to use the `./feature/index.ts` file instead."
}

export type TranslationFunctions = {
	feature: {
		/**
		 * {hours} h. {minutes} min.
		 */
		projectTimeDuration: (arg: { hours: number, minutes: number }) => LocalizedString
		/**
		 * Ungrouped
		 */
		projectTimeDefaultGroupName: () => LocalizedString
		/**
		 * Regex
		 */
		projectTimeRegexPlaceholder: () => LocalizedString
		/**
		 * Regular expression for grouping records. Must contain exactly one capture group.
		 */
		projectTimeRegexDescription: () => LocalizedString
		/**
		 * Regular expression error.
		 */
		projectTimeRegexErrorPrefix: () => LocalizedString
		/**
		 * Too many capture groups in the regular expression: actual amount - {actual}, expected - {expected}
		 */
		projectTimeRegexTooManyGroupsError: (arg: { actual: number, expected: number }) => LocalizedString
		/**
		 * Regular expression must contain a capture group
		 */
		projectTimeRegexNoGroupError: () => LocalizedString
	}
}

export type Formatters = {}
