name: Build and lint
on:
  push:
    branches: '**'

jobs:
  build-lint:
    name: Build and lint the extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build the extension
        uses: ./.github/actions/build-extension
