name: Build, sign and release extension
on:
  push:
    tags:
      - v*

jobs:
  build-release:
    name: Build and sign the extension, create new release
    runs-on: ubuntu-latest
    steps:
      - id: extract-version
        name: Extract the version from the tag
        run: echo "VERSION=${GITHUB_REF#refs\/tags\/v}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build the extension
        uses: ./.github/actions/build-extension
        with:
          version: ${{ steps.extract-version.outputs.VERSION }}

      - name: Sign the extension
        run: npm run sign:amo
        shell: bash
        env:
          AMO_API_KEY: ${{ secrets.AMO_API_KEY }}
          AMO_API_SECRET: ${{ secrets.AMO_API_SECRET }}
      
      - name: Create new release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: "*/*.xpi"
          name: Release v${{ steps.extract-version.outputs.VERSION }}
          generate_release_notes: true
