name: Push update
on:
  release:
    types:
      - released
      - created
      - edited
      - deleted
      - prereleased

jobs:
  push-update:
    name: Push update on release
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
