name: Push new version to the update manifest
on:
  release:
    types:
      - published

jobs:
  push-update-manifest:
    name: Push new version of the extension to the update manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Extract xpi asset link from the event payload
        id: jq-stuff
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'jq ".release.assets | map(select(.name? | test(\".*xpi\")))[0].browser_download_url" -r <<< "$EVENT_PAYLOAD_JSON"'
        env:
          EVENT_PAYLOAD_JSON: ${{ toJson(github.event) }}

      - name: Download the extension file
        uses: wei/wget@v1
        with:
          args: -O extension.xpi "$ASSET_URL"
        env:
          ASSET_URL: ${{ steps.jq-stuff.outputs.value }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: npm ci

      - name: Generate new update manifest
        run: >
          node script/update.js --updateLink "$ASSET_URL" --extensionFilePath "extension.xpi" --existingUpdateManifest "pages/updates.json" --newUpdateManifestPath "pages/updates.json"
        env:
          ASSET_URL: ${{ steps.jq-stuff.outputs.value }}

      - id: extract-version
        name: Extract the version from the tag name
        run: echo "::set-output name=VERSION::${TAG_NAME#v}"
        env:
          TAG_NAME: ${{ toJson(github.event.release.tag_name) }}

      - name: Create a pull request with the changes to the update manifest
        uses: gr2m/create-or-update-pull-request-action@v1.3.0
        with:
          title: Add update entry for v$VERSION_NAME
          body: |
            Add new update entry to the extension update manifest for release $VERSION_NAME

            Auto-generated by GitHub Action
          author: pull-request-github-action[bot] <pull-request-github-action[bot]@users.noreply.github.com>
          commit-message: Add update entry for $VERSION_NAME
          path: pages/
          labels: update manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NAME: ${{ steps.extract-version.outputs.VERSION }}
